---
abstract: 'To the extent that SOAP can be simple'
author:
  - 'Anders Nor Berle <berle@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SOAP-Simple
no_index:
  directory:
    - inc
requires:
  Moose: 0.73
  XML::Compile::SOAP: 2.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.00_01
